/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;

import controller.*;
import java.awt.Component;
import exception.InputKosongException;
import exception.InputSpecialAtributeException;
import javax.swing.JOptionPane;
import model.*;

public class LayananMainPanel extends javax.swing.JPanel {
    private LayananControl lc = new LayananControl();
    private LayananServis lyn = null;
    String actionKendaraan = null;
    int idLayanan = 0;
    private Component rootPane;
    
    public LayananMainPanel() {
        initComponents();
        setOpaque(false);
        showLayanan();
        setComponentsLayanan(false);
        setLayananEditDeleteButton(false);
        clearText();        
    }
    
    public void inputKosongKendaraanException() throws InputKosongException{
        if(namaLayananInputTextField.getText().isEmpty() || biayaLayananInputTextfield.getText().isEmpty())
            throw new InputKosongException();
    }

    public boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    public void setComponentsLayanan(boolean value){
        idLayananInputTextField.setEnabled(value);
        namaLayananInputTextField.setEnabled(value);
        biayaLayananInputTextfield.setEnabled(value);
        waktuInputTextfield.setEnabled(value);
    }
    
    public void setLayananEditDeleteButton(boolean value){
        barukanLayananButton.setEnabled(value);
        hapusLayananButton.setEnabled(value);
    }
    
    public void clearText(){
        idLayananInputTextField.setText("");
        namaLayananInputTextField.setText("");
        biayaLayananInputTextfield.setText("");
        searchLayananInputTextField.setText("");
    }
    
    public void showLayanan(){
        layananTextArea.setText("List Layanan: \n ============= \n"+lc.showAllStringLayanan());
    }
    
    private void doSearchLayanan(){
        if(searchLayananInputTextField.getText().isEmpty())
            return;
        
            lyn = lc.searchLayananById(Integer.parseInt(searchLayananInputTextField.getText()));
            
        if(lyn != null){
            setLayananEditDeleteButton(true);
            idLayananInputTextField.setText(Integer.toString(lyn.getIdLayanan()));
            namaLayananInputTextField.setText(lyn.getNamaLayanan());
            biayaLayananInputTextfield.setText(Float.toString(lyn.getBiaya()));
            waktuInputTextfield.setText(lyn.getWaktu());
        }else{
            JOptionPane.showMessageDialog(rootPane, "NOT FOUND !!!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        searchKendaraanInputPanel = new javax.swing.JPanel();
        searchLayananInputLabel = new javax.swing.JLabel();
        searchLayananInputTextField = new javax.swing.JTextField();
        searchLayananInputButton = new javax.swing.JButton();
        layananFormPanel = new javax.swing.JPanel();
        LayananButtonPanel = new javax.swing.JPanel();
        barukanLayananButton = new javax.swing.JButton();
        hapusLayananButton = new javax.swing.JButton();
        tambahLayananButton = new javax.swing.JButton();
        idLayananInputPanel = new javax.swing.JPanel();
        idLayananInputLabel = new javax.swing.JLabel();
        idLayananInputTextField = new javax.swing.JTextField();
        namaLayananInputPanel = new javax.swing.JPanel();
        namaLayananInputLabel = new javax.swing.JLabel();
        namaLayananInputTextField = new javax.swing.JTextField();
        hargaLayananInputPanel = new javax.swing.JPanel();
        biayaLayananInputLabel = new javax.swing.JLabel();
        biayaLayananInputTextfield = new javax.swing.JTextField();
        waktuInputPanel = new javax.swing.JPanel();
        waktuInputLabel = new javax.swing.JLabel();
        waktuInputTextfield = new javax.swing.JTextField();
        simpanKendaraanButton = new javax.swing.JButton();
        layananScrollPane = new javax.swing.JScrollPane();
        layananTextArea = new javax.swing.JTextArea();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchKendaraanInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchLayananInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchLayananInputLabel.setText("Pencarian Layanan");

        searchLayananInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchLayananInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchLayananInputTextFieldKeyPressed(evt);
            }
        });

        searchLayananInputButton.setBackground(new java.awt.Color(27, 26, 85));
        searchLayananInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchLayananInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchLayananInputButton.setText("Cari");
        searchLayananInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchLayananInputButtonActionPerformed(evt);
            }
        });

        layananFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        LayananButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanLayananButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanLayananButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanLayananButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanLayananButton.setText("Barukan");
        barukanLayananButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanLayananButtonActionPerformed(evt);
            }
        });

        hapusLayananButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusLayananButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusLayananButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusLayananButton.setText("Hapus");
        hapusLayananButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusLayananButtonActionPerformed(evt);
            }
        });

        tambahLayananButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahLayananButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahLayananButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahLayananButton.setText("Tambah");
        tambahLayananButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahLayananButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LayananButtonPanelLayout = new javax.swing.GroupLayout(LayananButtonPanel);
        LayananButtonPanel.setLayout(LayananButtonPanelLayout);
        LayananButtonPanelLayout.setHorizontalGroup(
            LayananButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayananButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahLayananButton)
                .addGap(18, 18, 18)
                .addComponent(barukanLayananButton)
                .addGap(18, 18, 18)
                .addComponent(hapusLayananButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        LayananButtonPanelLayout.setVerticalGroup(
            LayananButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayananButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LayananButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanLayananButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahLayananButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusLayananButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idLayananInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        idLayananInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idLayananInputLabel.setText("ID Kendaraan");

        idLayananInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idLayananInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idLayananInputTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idLayananInputPanelLayout = new javax.swing.GroupLayout(idLayananInputPanel);
        idLayananInputPanel.setLayout(idLayananInputPanelLayout);
        idLayananInputPanelLayout.setHorizontalGroup(
            idLayananInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idLayananInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idLayananInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idLayananInputTextField)
                    .addComponent(idLayananInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        idLayananInputPanelLayout.setVerticalGroup(
            idLayananInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idLayananInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idLayananInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idLayananInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaLayananInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        namaLayananInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaLayananInputLabel.setText("Nama Layanan");

        namaLayananInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout namaLayananInputPanelLayout = new javax.swing.GroupLayout(namaLayananInputPanel);
        namaLayananInputPanel.setLayout(namaLayananInputPanelLayout);
        namaLayananInputPanelLayout.setHorizontalGroup(
            namaLayananInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaLayananInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaLayananInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaLayananInputTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(namaLayananInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namaLayananInputPanelLayout.setVerticalGroup(
            namaLayananInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaLayananInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLayananInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaLayananInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hargaLayananInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        biayaLayananInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        biayaLayananInputLabel.setText("Biaya");

        biayaLayananInputTextfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        biayaLayananInputTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                biayaLayananInputTextfieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout hargaLayananInputPanelLayout = new javax.swing.GroupLayout(hargaLayananInputPanel);
        hargaLayananInputPanel.setLayout(hargaLayananInputPanelLayout);
        hargaLayananInputPanelLayout.setHorizontalGroup(
            hargaLayananInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hargaLayananInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hargaLayananInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(biayaLayananInputTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(biayaLayananInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hargaLayananInputPanelLayout.setVerticalGroup(
            hargaLayananInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hargaLayananInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(biayaLayananInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biayaLayananInputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        waktuInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        waktuInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        waktuInputLabel.setText("Waktu");

        waktuInputTextfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        waktuInputTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktuInputTextfieldActionPerformed(evt);
            }
        });
        waktuInputTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                waktuInputTextfieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout waktuInputPanelLayout = new javax.swing.GroupLayout(waktuInputPanel);
        waktuInputPanel.setLayout(waktuInputPanelLayout);
        waktuInputPanelLayout.setHorizontalGroup(
            waktuInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waktuInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(waktuInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waktuInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addGroup(waktuInputPanelLayout.createSequentialGroup()
                        .addComponent(waktuInputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        waktuInputPanelLayout.setVerticalGroup(
            waktuInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waktuInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waktuInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waktuInputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layananFormPanelLayout = new javax.swing.GroupLayout(layananFormPanel);
        layananFormPanel.setLayout(layananFormPanelLayout);
        layananFormPanelLayout.setHorizontalGroup(
            layananFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layananFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layananFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layananFormPanelLayout.createSequentialGroup()
                        .addComponent(LayananButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 308, Short.MAX_VALUE))
                    .addGroup(layananFormPanelLayout.createSequentialGroup()
                        .addGroup(layananFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(namaLayananInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idLayananInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layananFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(waktuInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hargaLayananInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layananFormPanelLayout.setVerticalGroup(
            layananFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layananFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LayananButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layananFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idLayananInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaLayananInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layananFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaLayananInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waktuInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout searchKendaraanInputPanelLayout = new javax.swing.GroupLayout(searchKendaraanInputPanel);
        searchKendaraanInputPanel.setLayout(searchKendaraanInputPanelLayout);
        searchKendaraanInputPanelLayout.setHorizontalGroup(
            searchKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchKendaraanInputPanelLayout.createSequentialGroup()
                .addGroup(searchKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchKendaraanInputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(searchKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchLayananInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(searchKendaraanInputPanelLayout.createSequentialGroup()
                                .addComponent(searchLayananInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchLayananInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 531, Short.MAX_VALUE))))
                    .addGroup(searchKendaraanInputPanelLayout.createSequentialGroup()
                        .addComponent(layananFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 604, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchKendaraanInputPanelLayout.setVerticalGroup(
            searchKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchKendaraanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchLayananInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchLayananInputTextField)
                    .addComponent(searchLayananInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layananFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        simpanKendaraanButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanKendaraanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanKendaraanButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanKendaraanButton.setText("Simpan");
        simpanKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKendaraanButtonActionPerformed(evt);
            }
        });

        layananScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        layananTextArea.setColumns(20);
        layananTextArea.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        layananTextArea.setRows(5);
        layananTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        layananScrollPane.setViewportView(layananTextArea);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchKendaraanInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(layananScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simpanKendaraanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchKendaraanInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simpanKendaraanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(layananScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchLayananInputTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchLayananInputTextFieldKeyPressed
        
    }//GEN-LAST:event_searchLayananInputTextFieldKeyPressed

    private void searchLayananInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchLayananInputButtonActionPerformed
        doSearchLayanan();
    }//GEN-LAST:event_searchLayananInputButtonActionPerformed

    private void barukanLayananButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanLayananButtonActionPerformed
        actionKendaraan = "update";
        setComponentsLayanan(true);
        idLayananInputTextField.setEnabled(false);
    }//GEN-LAST:event_barukanLayananButtonActionPerformed

    private void hapusLayananButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusLayananButtonActionPerformed
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Hapus ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if( opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION)
            return;
        
        lc.deleteDataLayanan(Integer.parseInt(idLayananInputTextField.getText()));
        clearText();
        setLayananEditDeleteButton(false);
        setComponentsLayanan(false);
        showLayanan();
    }//GEN-LAST:event_hapusLayananButtonActionPerformed

    private void tambahLayananButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahLayananButtonActionPerformed
        actionKendaraan = "add";
        clearText();
        setLayananEditDeleteButton(false);
        setComponentsLayanan(true);
        setLayananEditDeleteButton(false);
        
        idLayananInputTextField.setEnabled(false);
    }//GEN-LAST:event_tambahLayananButtonActionPerformed

    private void idLayananInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idLayananInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idLayananInputTextFieldActionPerformed

    private void biayaLayananInputTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_biayaLayananInputTextfieldKeyTyped

    }//GEN-LAST:event_biayaLayananInputTextfieldKeyTyped

    private void simpanKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanKendaraanButtonActionPerformed
        if(actionKendaraan == null)
            return;
        try{
            inputKosongKendaraanException();
            
            if(JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionKendaraan + "?") == JOptionPane.CLOSED_OPTION)
                return;

            switch (actionKendaraan){
                case "add":
//                    public LayananServis(String namaLayanan, float biaya, String waktu)
                    lyn = new LayananServis(namaLayananInputTextField.getText(), Float.parseFloat(biayaLayananInputTextfield.getText()), 
                            waktuInputTextfield.getText());
                    lc.insertDataLayanan(lyn);
                    clearText();
                    setLayananEditDeleteButton(false);
                    setComponentsLayanan(false);
                    showLayanan();
                    break;
                case "update":
                    lyn = new LayananServis(namaLayananInputTextField.getText(), Float.parseFloat(biayaLayananInputTextfield.getText()), 
                            waktuInputTextfield.getText());
                    lc.updateDataLayanan(lyn, lyn.getIdLayanan());
                    clearText();
                    setLayananEditDeleteButton(false);
                    setComponentsLayanan(false);
                    showLayanan();
                    break;
                default:
                    break;
            }
            actionKendaraan = null;
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(rootPane, e.message());
        }
    }//GEN-LAST:event_simpanKendaraanButtonActionPerformed

    private void waktuInputTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_waktuInputTextfieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_waktuInputTextfieldKeyTyped

    private void waktuInputTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktuInputTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waktuInputTextfieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LayananButtonPanel;
    private javax.swing.JButton barukanLayananButton;
    private javax.swing.JLabel biayaLayananInputLabel;
    private javax.swing.JTextField biayaLayananInputTextfield;
    private javax.swing.JButton hapusLayananButton;
    private javax.swing.JPanel hargaLayananInputPanel;
    private javax.swing.JLabel idLayananInputLabel;
    private javax.swing.JPanel idLayananInputPanel;
    private javax.swing.JTextField idLayananInputTextField;
    private javax.swing.JPanel layananFormPanel;
    private javax.swing.JScrollPane layananScrollPane;
    private javax.swing.JTextArea layananTextArea;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaLayananInputLabel;
    private javax.swing.JPanel namaLayananInputPanel;
    private javax.swing.JTextField namaLayananInputTextField;
    private javax.swing.JPanel searchKendaraanInputPanel;
    private javax.swing.JButton searchLayananInputButton;
    private javax.swing.JLabel searchLayananInputLabel;
    private javax.swing.JTextField searchLayananInputTextField;
    private javax.swing.JButton simpanKendaraanButton;
    private javax.swing.JButton tambahLayananButton;
    private javax.swing.JLabel waktuInputLabel;
    private javax.swing.JPanel waktuInputPanel;
    private javax.swing.JTextField waktuInputTextfield;
    // End of variables declaration//GEN-END:variables
}
